apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: feheroes-svc-vs
  namespace: heroes-ns
spec:
  hosts:
  - "feheroes-svc.heroes-ns.svc.cluster.local"
  gateways:
  - feheroes-svc-gw
  - mesh
  http:
  - route:
    - destination:
        host: feheroes-svc